
export const generateSitemap = () => {
  const baseUrl = 'https://dripmuse.com';
  const currentDate = new Date().toISOString().split('T')[0];
  
  const pages = [
    { url: '', priority: '1.0', changeFreq: 'weekly' },
    { url: '/auth', priority: '0.8', changeFreq: 'monthly' },
    { url: '/terms', priority: '0.3', changeFreq: 'yearly' },
    { url: '/privacy', priority: '0.3', changeFreq: 'yearly' },
  ];

  const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${pages.map(page => `  <url>
    <loc>${baseUrl}${page.url}</loc>
    <lastmod>${currentDate}</lastmod>
    <changefreq>${page.changeFreq}</changefreq>
    <priority>${page.priority}</priority>
  </url>`).join('\n')}
</urlset>`;

  return sitemap;
};

export const generateRobotsTxt = () => {
  const baseUrl = 'https://dripmuse.com';
  
  return `User-agent: *
Allow: /
Disallow: /dashboard
Disallow: /wardrobe
Disallow: /recommendations
Disallow: /analytics
Disallow: /edit-profile

Sitemap: ${baseUrl}/sitemap.xml`;
};

// SEO-friendly URL slugs
export const createSlug = (text: string): string => {
  return text
    .toLowerCase()
    .trim()
    .replace(/[^\w\s-]/g, '')
    .replace(/[\s_-]+/g, '-')
    .replace(/^-+|-+$/g, '');
};

// Schema.org structured data generators
export const generatePersonSchema = (profile: any) => {
  return {
    "@context": "https://schema.org",
    "@type": "Person",
    "name": profile?.display_name || "DripMuse User",
    "description": "Fashion enthusiast using DripMuse AI styling platform"
  };
};

export const generateFashionRecommendationSchema = (recommendations: any[]) => {
  return {
    "@context": "https://schema.org",
    "@type": "ItemList",
    "name": "AI Fashion Recommendations",
    "description": "Personalized outfit recommendations generated by DripMuse AI",
    "numberOfItems": recommendations.length,
    "itemListElement": recommendations.map((item, index) => ({
      "@type": "ListItem",
      "position": index + 1,
      "item": {
        "@type": "Product",
        "name": item.name || `Outfit Recommendation ${index + 1}`,
        "description": item.description || "AI-curated fashion recommendation"
      }
    }))
  };
};
