// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dskruszbxlndmnhwcudx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRza3J1c3pieGxuZG1uaHdjdWR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MTUxMjIsImV4cCI6MjA2NzI5MTEyMn0.yHWR5siVSTzh4CgHPzpBNQD6Swuk0FqvY_a8QwaDyZs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});